
SET search_path TO tuto;


-- Schéma

DROP TABLE compte;
DROP TABLE benevole;
DROP TABLE participant;
DROP TABLE equipe;
DROP TABLE poste;
DROP TABLE typePoste;
DROP TABLE typeCourse;
DROP TABLE categorieCourse;
DROP TABLE personne;



-- Tables

CREATE TABLE compte (
	id			INT				GENERATED BY DEFAULT AS IDENTITY,
	pseudo			VARCHAR(20) NOT NULL,
	motdepasse		VARCHAR(20) NOT NULL,
	mail			VARCHAR(20) NOT NULL
);

CREATE TABLE personne (
	id			INT				GENERATED BY DEFAULT AS IDENTITY,
	nom			VARCHAR(25)  	NOT NULL,
	prenom			VARCHAR(25) 	NOT NULL,
	dateNaissance		DATE,
	mail			VARCHAR(50),
	numTel			VARCHAR(20) NOT NULL,
	adresse 		VARCHAR(60),
	ville			VARCHAR(58),
	mineur			BOOLEAN,
	autorisationParentale	BOOLEAN,	

	PRIMARY KEY (id)
);

CREATE TABLE categorieCourse (
	id			INT 	GENERATED BY DEFAULT AS IDENTITY,
	nom			VARCHAR(50),
	
	PRIMARY KEY (id)
);

CREATE TABLE typeCourse (
	id			INT 	GENERATED BY DEFAULT AS IDENTITY,
	nom			VARCHAR(50),
	
	PRIMARY KEY (id)
);

CREATE TABLE typePoste (
	id			INT 	GENERATED BY DEFAULT AS IDENTITY,
	nom			VARCHAR(50),
	
	PRIMARY KEY (id)
);

CREATE TABLE poste (
	id			INT 	GENERATED BY DEFAULT AS IDENTITY,	
	nom 			VARCHAR(50), 
	typePoste		INT,
	heureD			DATETIME,
	heureF			DATETIME,

	PRIMARY KEY (id),
	FOREIGN KEY (typePoste) REFERENCES typePoste (id)
);

CREATE TABLE equipe (
	id			INT 	GENERATED BY DEFAULT AS IDENTITY,	
	nom 			VARCHAR(50), 
	nbBouffe		INT, 
	typeCourse		INT, 
	catCourse		INT,

	PRIMARY KEY (id),
	FOREIGN KEY (typeCourse) REFERENCES typeCourse(id),
	FOREIGN KEY (catCourse) REFERENCES categorieCourse (id)
);

CREATE TABLE participant (
	club 			VARCHAR(50),
	capitaine		BOOLEAN,
	paiement		BOOLEAN,
	attestation		BOOLEAN,
	dossierMedic		BOOLEAN,
	equipe 			INT,

	FOREIGN KEY (equipe) REFERENCES equipe(id),
) INHERITS (personne);

CREATE TABLE benevole (
	permis			BOOLEAN,
	membre			BOOLEAN,	
	
	heureD			DATETIME,
	heureF			DATETIME,
) INHERITS (personne);
