

SET search_path TO projet;


-- Schéma


DROP TABLE IF EXISTS compte;
DROP TABLE IF EXISTS benevole;
DROP TABLE IF EXISTS participant;
DROP TABLE IF EXISTS equipe;
DROP TABLE IF EXISTS poste;
DROP TABLE IF EXISTS typePoste;
DROP TABLE IF EXISTS typeCourse;
DROP TABLE IF EXISTS categorieCourse;
DROP TABLE IF EXISTS personne;

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;

-- Tables

CREATE TABLE compte (
	id			INT				GENERATED BY DEFAULT AS IDENTITY,
	pseudo			VARCHAR(20) NOT NULL,
	motdepasse		VARCHAR(20) NOT NULL,
	mail			VARCHAR(20) NOT NULL
);

CREATE TABLE personne (
	id			INT				GENERATED BY DEFAULT AS IDENTITY,
	nom			VARCHAR(25)  	NOT NULL,
	prenom			VARCHAR(25) 	NOT NULL,
	dateNaissance		DATE,
	mail			VARCHAR(50),
	numTel			VARCHAR(20) NOT NULL,
	adresse 		VARCHAR(60),
	ville			VARCHAR(58),
	mineur			BOOLEAN,
	autorisationParentale	BOOLEAN,	

	PRIMARY KEY (id)
);

CREATE TABLE categorieCourse (
	id			INT 	GENERATED BY DEFAULT AS IDENTITY,
	nom			VARCHAR(50),
	
	PRIMARY KEY (id)
);

CREATE TABLE typeCourse (
	id			INT 	GENERATED BY DEFAULT AS IDENTITY,
	nom			VARCHAR(50),
	
	PRIMARY KEY (id)
);

CREATE TABLE typePoste (
	id			INT 	GENERATED BY DEFAULT AS IDENTITY,
	nom			VARCHAR(50),
	
	PRIMARY KEY (id)
);

CREATE TABLE poste (
	id			INT 	GENERATED BY DEFAULT AS IDENTITY,	
	nom 			VARCHAR(50), 
	typePoste		INT,
	heureD			TIME,
	heureF			TIME ,

	PRIMARY KEY (id),
	FOREIGN KEY (typePoste) REFERENCES typePoste (id)
);

CREATE TABLE equipe (
	id			INT 	GENERATED BY DEFAULT AS IDENTITY,	
	nom 			VARCHAR(50), 
	nbBouffe		INT, 
	typeCourse		INT, 
	catCourse		INT,

	PRIMARY KEY (id),
	FOREIGN KEY (typeCourse) REFERENCES typeCourse(id),
	FOREIGN KEY (catCourse) REFERENCES categorieCourse (id)
);

CREATE TABLE participant (
	club 			VARCHAR(50),
	capitaine		BOOLEAN,
	paiement		BOOLEAN,
	attestation		BOOLEAN,
	dossierMedic		BOOLEAN,
	equipe 			INT,

	FOREIGN KEY (equipe) REFERENCES equipe(id)
) INHERITS (personne);

CREATE TABLE benevole (
	permis			BOOLEAN,
	membre			BOOLEAN,	
	
	heureD			TIME,
	heureF			TIME
) INHERITS (personne);
